Databases:
    SqlServer:
        Server: localhost\SQLEXPRESS
        Port: 1433
        Database: Hardware_Online_Store
        IntegratedSecurity: true
        UserName: null
        Password: null
        TrustedConnection: true
        TrustServerCertificate: true
        ConnectionTimeout: 00:00:15
        MaxPoolSize: 100
Logging:
    Path: C:\Users\рс\AppData\Local\Temp\HardwareOnlineStore\Logging\AppLog.txt
    ReadOnly: true
Caching:
    Path: C:\Users\рс\AppData\Local\Temp\HardwareOnlineStore\Caching
    ReadOnly: true